ProjetoLanchesMVC/ProjetoLanchesMVC/Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoLanchesMVC.Models;
using ProjetoLanchesMVC.Repositories;
using ProjetoLanchesMVC.Repositories.Interfaces;
using ProjetoLanchesMVC.ViewModels;

namespace ProjetoLanchesMVC.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }

        public IActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p=> p.LancheId == lancheId);

            if(lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
    }
}

ProjetoLanchesMVC/ProjetoLanchesMVC/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjetoLanchesMVC.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjetoLanchesMVC/ProjetoLanchesMVC/Controllers/LancheController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoLanchesMVC.Models;
using ProjetoLanchesMVC.Repositories.Interfaces;
using ProjetoLanchesMVC.ViewModels;

namespace ProjetoLanchesMVC.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                //if(string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Normal"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Natural"))
                //        .OrderBy(l => l.Nome);
                //}
                lanches = _lancheRepository.Lanches
                    .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                    .OrderBy(l => l.Nome);
                categoriaAtual = categoria;
            }

            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l=> l.LancheId == lancheId);

            return View(lanche);
        }
    }
}

ProjetoLanchesMVC/ProjetoLanchesMVC/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner" style="border-radius: 35px;">
    <div class="carousel-item active">
      <img src="~/images/1.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/2.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/3.png" class="d-block w-100"  alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

ProjetoLanchesMVC/ProjetoLanchesMVC/Views/Shared/_LanchesResumo.cshtml
@model Lanche
<div class="col-sm-4 col-md-4 col-lg-4">
    @*<p><img src="@Model.ImagemUrl" class="img-fluid"></p>*@

    <a asp-controller="Lanche" asp-action="Details"
    asp-route-lancheId="@Model.LancheId"><img src="@Model.ImagemUrl" class="img-fluid"></a>

    <h3>Preço: @Model.Preco.ToString("c")</h3>

    <h4><a asp-controller="Lanche" asp-action="Details"
    asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
    </h4>

    <p>@Model.DescricaoCurta</p>
      <div>
        <p class="button">
            <a class="btn btn-orange-ff8a66_2" id="cartButton" asp-controller="CarrinhoCompra" 
            asp-action="AdicionarItemNoCarrinhoCompra" asp-route-LancheId="@Model.LancheId">
            Incluir no Carrinho
        </a>
        </p>

</div>
</div>

ProjetoLanchesMVC/ProjetoLanchesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ProjetoLanchesMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoLanchesMVC.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/kurama.ico" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: orangered;">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    ProjetoLanchesMVC
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    @await Component.InvokeAsync("CategoriaMenu")
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    @*<a class="nav-link text-white" asp-area="" asp-controller="Lanche" asp-action="List">Lanches</a>*@
                    <a class="nav-link text-white" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoLanchesMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>